//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fosol.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Multilingual {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Multilingual() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fosol.Common.Resources.Multilingual", typeof(Multilingual).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &quot;{0}&quot; is invalid..
        /// </summary>
        internal static string Exception_Assembly_Is_Invalid {
            get {
                return ResourceManager.GetString("Exception_Assembly_Is_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocrop height or width must be greater than zero..
        /// </summary>
        internal static string Exception_AutocropScale {
            get {
                return ResourceManager.GetString("Exception_AutocropScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration does not contain key &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_Config_Does_Not_Contain_Key {
            get {
                return ResourceManager.GetString("Exception_Config_Does_Not_Contain_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; configuration section does not exist..
        /// </summary>
        internal static string Exception_Configuration_Section_Not_Found {
            get {
                return ResourceManager.GetString("Exception_Configuration_Section_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination is too small to accept &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_Destination_Too_Small {
            get {
                return ResourceManager.GetString("Exception_Destination_Too_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; was not found..
        /// </summary>
        internal static string Exception_File_Not_Found {
            get {
                return ResourceManager.GetString("Exception_File_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FormatKeyword &quot;{0}&quot; already exists..
        /// </summary>
        internal static string Exception_FormatElement_Already_Exists {
            get {
                return ResourceManager.GetString("Exception_FormatElement_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format keyword &quot;{0}&quot; attribute &quot;{1}&quot; is required..
        /// </summary>
        internal static string Exception_FormatElement_Attribute_Required {
            get {
                return ResourceManager.GetString("Exception_FormatElement_Attribute_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FormatKeyword &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string Exception_FormatElement_Does_Not_Exist {
            get {
                return ResourceManager.GetString("Exception_FormatElement_Does_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FormatKeyword &quot;{0}&quot; is not valid..
        /// </summary>
        internal static string Exception_FormatElement_Is_Not_Valid {
            get {
                return ResourceManager.GetString("Exception_FormatElement_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be less than or equal to the original image height..
        /// </summary>
        internal static string Exception_ImageHelper_Invalid_Height {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_Invalid_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must have at least one property value set greater than &apos;0&apos;..
        /// </summary>
        internal static string Exception_ImageHelper_Invalid_Plot {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_Invalid_Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be between &apos;0&apos; and &apos;100&apos;..
        /// </summary>
        internal static string Exception_ImageHelper_Invalid_Quality {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_Invalid_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be greater than or equal to &apos;0&apos;..
        /// </summary>
        internal static string Exception_ImageHelper_Invalid_Resize_Height {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_Invalid_Resize_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be greater than or equal to &apos;0&apos;..
        /// </summary>
        internal static string Exception_ImageHelper_Invalid_Resize_Width {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_Invalid_Resize_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be less than or equal to the original image width..
        /// </summary>
        internal static string Exception_ImageHelper_Invalid_Width {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_Invalid_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be greater than or equal to &apos;0&apos; and less than the original image width..
        /// </summary>
        internal static string Exception_ImageHelper_Invalid_X {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_Invalid_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must plot within the original image width..
        /// </summary>
        internal static string Exception_ImageHelper_Invalid_XWidth {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_Invalid_XWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be greater than or equal to &apos;0&apos; and less than the original image height..
        /// </summary>
        internal static string Exception_ImageHelper_Invalid_Y {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_Invalid_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must plot within the original image height..
        /// </summary>
        internal static string Exception_ImageHelper_Invalid_YHeight {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_Invalid_YHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml NodeType is not valid for CDATA.  Expecting text or cdata..
        /// </summary>
        internal static string Exception_Invalid_CData {
            get {
                return ResourceManager.GetString("Exception_Invalid_CData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must have width or height set to greater than &apos;0&apos;..
        /// </summary>
        internal static string Exception_Invalid_Size {
            get {
                return ResourceManager.GetString("Exception_Invalid_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property value has already been set and can only be initialized once..
        /// </summary>
        internal static string Exception_SetOnce_AlreadySet {
            get {
                return ResourceManager.GetString("Exception_SetOnce_AlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property value must be set before it can be retrieved..
        /// </summary>
        internal static string Exception_SetOnce_NotSet {
            get {
                return ResourceManager.GetString("Exception_SetOnce_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be readable (CanRead=true)..
        /// </summary>
        internal static string Exception_Stream_IsCanRead {
            get {
                return ResourceManager.GetString("Exception_Stream_IsCanRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be seekable (CanSeek=true)..
        /// </summary>
        internal static string Exception_Stream_IsCanSeek {
            get {
                return ResourceManager.GetString("Exception_Stream_IsCanSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be writable (CanWrite=true)..
        /// </summary>
        internal static string Exception_Stream_IsCanWrite {
            get {
                return ResourceManager.GetString("Exception_Stream_IsCanWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many occurances of attribute &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_Too_Many_Of_Attribute {
            get {
                return ResourceManager.GetString("Exception_Too_Many_Of_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; contains more than one key value pair..
        /// </summary>
        internal static string Exception_Too_Many_Pairs {
            get {
                return ResourceManager.GetString("Exception_Too_Many_Pairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type must be of type String..
        /// </summary>
        internal static string Exception_Type_Must_Be_String {
            get {
                return ResourceManager.GetString("Exception_Type_Must_Be_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; value must end with &quot;{1}&quot;..
        /// </summary>
        internal static string Exception_Validation_Argument_EndsWith {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must have an attribute of type &quot;{1}&quot;..
        /// </summary>
        internal static string Exception_Validation_Argument_HasAttribute {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_HasAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be assignable to type &quot;{1}&quot;..
        /// </summary>
        internal static string Exception_Validation_Argument_IsAssignable {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; is not a valid email..
        /// </summary>
        internal static string Exception_Validation_Argument_IsEmail {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; must be equal to the specified validValue..
        /// </summary>
        internal static string Exception_Validation_Argument_IsEqual {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be false..
        /// </summary>
        internal static string Exception_Validation_Argument_IsFalse {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; is not a valid FSA..
        /// </summary>
        internal static string Exception_Validation_Argument_IsFSA {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsFSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; is not a valid LDU..
        /// </summary>
        internal static string Exception_Validation_Argument_IsLDU {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsLDU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; cannot be empty..
        /// </summary>
        internal static string Exception_Validation_Argument_IsNotEmpty {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; cannot be null, empty or whitespace..
        /// </summary>
        internal static string Exception_Validation_Argument_IsNotEmptyOrWhitespace {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsNotEmptyOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; cannot be null..
        /// </summary>
        internal static string Exception_Validation_Argument_IsNotNull {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; cannot be null or empty..
        /// </summary>
        internal static string Exception_Validation_Argument_IsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; is not a valid value..
        /// </summary>
        internal static string Exception_Validation_Argument_IsNotValue {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsNotValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; is not a valid number..
        /// </summary>
        internal static string Exception_Validation_Argument_IsNumber {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; is not a valid postal code..
        /// </summary>
        internal static string Exception_Validation_Argument_IsPostalCode {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be true..
        /// </summary>
        internal static string Exception_Validation_Argument_IsTrue {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be of type &quot;{1}&quot;..
        /// </summary>
        internal static string Exception_Validation_Argument_IsType {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; is not a valid URI..
        /// </summary>
        internal static string Exception_Validation_Argument_IsUri {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; must be a valid index position..
        /// </summary>
        internal static string Exception_Validation_Argument_IsValidIndexPosition {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsValidIndexPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; is not a valid password..
        /// </summary>
        internal static string Exception_Validation_Argument_IsValidPassword {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; has an invalid value..
        /// </summary>
        internal static string Exception_Validation_Argument_IsValue {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_IsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be less than or equal to &quot;{1}&quot;..
        /// </summary>
        internal static string Exception_Validation_Argument_MaxRange {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_MaxRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be greater than or equal to &quot;{1}&quot;..
        /// </summary>
        internal static string Exception_Validation_Argument_MinRange {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_MinRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be greater than or equal to &quot;{1}&quot; and less than or equal to &quot;{2}&quot;..
        /// </summary>
        internal static string Exception_Validation_Argument_Range {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; value must start with &quot;{1}&quot;..
        /// </summary>
        internal static string Exception_Validation_Argument_StartsWith {
            get {
                return ResourceManager.GetString("Exception_Validation_Argument_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must end with &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_Validation_Value_EndsWith {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must have an attribute of type &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_Validation_Value_HasAttribute {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_HasAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value type must be assignable from type &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_Validation_Value_IsAssignable {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &quot;[0}&quot; is not a valid email..
        /// </summary>
        internal static string Exception_Validation_Value_IsEmail {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not equal..
        /// </summary>
        internal static string Exception_Validation_Value_IsEqual {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be false..
        /// </summary>
        internal static string Exception_Validation_Value_IsFalse {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &quot;{0}&quot; is not a valid FSA..
        /// </summary>
        internal static string Exception_Validation_Value_IsFSA {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsFSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &quot;{0}&quot; is not a valid LDU..
        /// </summary>
        internal static string Exception_Validation_Value_IsLDU {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsLDU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null, empty or whitespace..
        /// </summary>
        internal static string Exception_Validation_Value_IsNotEmptyOrWhitespace {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsNotEmptyOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null..
        /// </summary>
        internal static string Exception_Validation_Value_IsNotNull {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        internal static string Exception_Validation_Value_IsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be equal to &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_Validation_Value_IsNotValue {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsNotValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &quot;{0}&quot; is not a number..
        /// </summary>
        internal static string Exception_Validation_Value_IsNumber {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &quot;{0}&quot; is not a valid postal code..
        /// </summary>
        internal static string Exception_Validation_Value_IsPostalCode {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be true..
        /// </summary>
        internal static string Exception_Validation_Value_IsTrue {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be of type &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_Validation_Value_IsType {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &quot;{0}&quot; is not a valid URI..
        /// </summary>
        internal static string Exception_Validation_Value_IsUri {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value does meet the password strength requirements..
        /// </summary>
        internal static string Exception_Validation_Value_IsValidPassword {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &quot;{0}&quot; is not valid..
        /// </summary>
        internal static string Exception_Validation_Value_IsValue {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_IsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be less than or equal to &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_Validation_Value_MaxRange {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_MaxRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than or equal to &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_Validation_Value_MinRange {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_MinRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than or equal to &quot;{0}&quot; and less than or equal to &quot;{1}&quot;..
        /// </summary>
        internal static string Exception_Validation_Value_Range {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must start with &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_Validation_Value_StartsWith {
            get {
                return ResourceManager.GetString("Exception_Validation_Value_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; is too small to accept value..
        /// </summary>
        internal static string Exception_Value_Too_Small {
            get {
                return ResourceManager.GetString("Exception_Value_Too_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; must be a valid &apos;{1}&apos; value..
        /// </summary>
        internal static string Iniitialization_Convert_InvalidCastException {
            get {
                return ResourceManager.GetString("Iniitialization_Convert_InvalidCastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; cannot be null..
        /// </summary>
        internal static string Initialization_Convert_ArgumentNullException {
            get {
                return ResourceManager.GetString("Initialization_Convert_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; must be a valid format to convert to the desired &apos;{1}&apos; type..
        /// </summary>
        internal static string Initialization_Convert_FormatException {
            get {
                return ResourceManager.GetString("Initialization_Convert_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; must be a valid &apos;{1}&apos; value..
        /// </summary>
        internal static string Initialization_Convert_OverflowException {
            get {
                return ResourceManager.GetString("Initialization_Convert_OverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}   --- End of inner exception stack trace ---{0}.
        /// </summary>
        internal static string Value_Exception_ToString {
            get {
                return ResourceManager.GetString("Value_Exception_ToString", resourceCulture);
            }
        }
    }
}
