//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fosol.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fosol.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &quot;{0}&quot; is required..
        /// </summary>
        internal static string Exception_AttributeMissing {
            get {
                return ResourceManager.GetString("Exception_AttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocrop height or width must be greater than zero..
        /// </summary>
        internal static string Exception_AutocropScale {
            get {
                return ResourceManager.GetString("Exception_AutocropScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration does not contain key &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_ConfigDoesNotContainKey {
            get {
                return ResourceManager.GetString("Exception_ConfigDoesNotContainKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; configuration section does not exist..
        /// </summary>
        internal static string Exception_ConfigurationSectionNotFound {
            get {
                return ResourceManager.GetString("Exception_ConfigurationSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter value must end with &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_EndsWith {
            get {
                return ResourceManager.GetString("Exception_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; was not found..
        /// </summary>
        internal static string Exception_FileNotFound {
            get {
                return ResourceManager.GetString("Exception_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be less than or equal to the original image height..
        /// </summary>
        internal static string Exception_ImageHelper_InvalidHeight {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_InvalidHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must have at least one property value set greater than &apos;0&apos;..
        /// </summary>
        internal static string Exception_ImageHelper_InvalidPlot {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_InvalidPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be between &apos;0&apos; and &apos;100&apos;..
        /// </summary>
        internal static string Exception_ImageHelper_InvalidQuality {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_InvalidQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be greater than or equal to &apos;0&apos;..
        /// </summary>
        internal static string Exception_ImageHelper_InvalidResizeHeight {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_InvalidResizeHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be greater than or equal to &apos;0&apos;..
        /// </summary>
        internal static string Exception_ImageHelper_InvalidResizeWidth {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_InvalidResizeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be less than or equal to the original image width..
        /// </summary>
        internal static string Exception_ImageHelper_InvalidWidth {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_InvalidWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be greater than or equal to &apos;0&apos; and less than the original image width..
        /// </summary>
        internal static string Exception_ImageHelper_InvalidX {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_InvalidX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters &quot;{0}&quot; must plot within the original image width..
        /// </summary>
        internal static string Exception_ImageHelper_InvalidXWidth {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_InvalidXWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be greater than or equal to &apos;0&apos; and less than the original image height..
        /// </summary>
        internal static string Exception_ImageHelper_InvalidY {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_InvalidY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters &quot;{0}&quot; must plot within the original image height..
        /// </summary>
        internal static string Exception_ImageHelper_InvalidYHeight {
            get {
                return ResourceManager.GetString("Exception_ImageHelper_InvalidYHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml NodeType is not valid for CDATA.  Expecting text or cdata..
        /// </summary>
        internal static string Exception_InvalidCData {
            get {
                return ResourceManager.GetString("Exception_InvalidCData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must have width or height set to greater than &apos;0&apos;..
        /// </summary>
        internal static string Exception_InvalidSize {
            get {
                return ResourceManager.GetString("Exception_InvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; has an invalid value..
        /// </summary>
        internal static string Exception_InvalidValue {
            get {
                return ResourceManager.GetString("Exception_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be null or empty..
        /// </summary>
        internal static string Exception_NotNullOrEmpty {
            get {
                return ResourceManager.GetString("Exception_NotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service error occured.  Please inspect the Fault property for details..
        /// </summary>
        internal static string Exception_ServiceFault {
            get {
                return ResourceManager.GetString("Exception_ServiceFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter value must start with &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_StartsWith {
            get {
                return ResourceManager.GetString("Exception_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be readable (CanRead=true)..
        /// </summary>
        internal static string Exception_Stream_IsCanRead {
            get {
                return ResourceManager.GetString("Exception_Stream_IsCanRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be seekable (CanSeek=true)..
        /// </summary>
        internal static string Exception_Stream_IsCanSeek {
            get {
                return ResourceManager.GetString("Exception_Stream_IsCanSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be writable (CanWrite=true)..
        /// </summary>
        internal static string Exception_Stream_IsCanWrite {
            get {
                return ResourceManager.GetString("Exception_Stream_IsCanWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many occurances of attribute &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_TooManyOfAttribute {
            get {
                return ResourceManager.GetString("Exception_TooManyOfAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; contains more than one key value pair..
        /// </summary>
        internal static string Exception_TooManyPairs {
            get {
                return ResourceManager.GetString("Exception_TooManyPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type must be of type String..
        /// </summary>
        internal static string Exception_TypeMustBeString {
            get {
                return ResourceManager.GetString("Exception_TypeMustBeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; is too small to accept value..
        /// </summary>
        internal static string Exception_ValueToSmall {
            get {
                return ResourceManager.GetString("Exception_ValueToSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}   --- End of inner exception stack trace ---{0}.
        /// </summary>
        internal static string Value_ExceptionToString {
            get {
                return ResourceManager.GetString("Value_ExceptionToString", resourceCulture);
            }
        }
    }
}
