//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fosol.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fosol.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &quot;{0}&quot; is required..
        /// </summary>
        internal static string Exception_AttributeMissing {
            get {
                return ResourceManager.GetString("Exception_AttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocrop height or width must be greater than zero..
        /// </summary>
        internal static string Exception_AutocropScale {
            get {
                return ResourceManager.GetString("Exception_AutocropScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration does not contain key &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_ConfigDoesNotContainKey {
            get {
                return ResourceManager.GetString("Exception_ConfigDoesNotContainKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter value must end with &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_EndsWith {
            get {
                return ResourceManager.GetString("Exception_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml NodeType is not valid for CDATA.  Expecting text or cdata..
        /// </summary>
        internal static string Exception_InvalidCData {
            get {
                return ResourceManager.GetString("Exception_InvalidCData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be null or empty..
        /// </summary>
        internal static string Exception_NotNullOrEmpty {
            get {
                return ResourceManager.GetString("Exception_NotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service error occured.  Please inspect the Fault property for details..
        /// </summary>
        internal static string Exception_ServiceFault {
            get {
                return ResourceManager.GetString("Exception_ServiceFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter value must start with &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_StartsWith {
            get {
                return ResourceManager.GetString("Exception_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many occurances of attribute &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_TooManyOfAttribute {
            get {
                return ResourceManager.GetString("Exception_TooManyOfAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; contains more than one key value pair..
        /// </summary>
        internal static string Exception_TooManyPairs {
            get {
                return ResourceManager.GetString("Exception_TooManyPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type must be of type String..
        /// </summary>
        internal static string Exception_TypeMustBeString {
            get {
                return ResourceManager.GetString("Exception_TypeMustBeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; has an invalid value..
        /// </summary>
        internal static string Exception_ValueInvalid {
            get {
                return ResourceManager.GetString("Exception_ValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; is too small to accept value..
        /// </summary>
        internal static string Exception_ValueToSmall {
            get {
                return ResourceManager.GetString("Exception_ValueToSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}   --- End of inner exception stack trace ---{0}.
        /// </summary>
        internal static string ExceptionExtensions_ExceptionToString {
            get {
                return ResourceManager.GetString("ExceptionExtensions_ExceptionToString", resourceCulture);
            }
        }
    }
}
